# Usa una imagen oficial de PHP con Apache
FROM php:8.2.31-apache

# Instalar extensiones necesarias
RUN docker-php-ext-install pdo pdo_mysql

# Copiar todo el código de tu proyecto
COPY . /var/www/html